### ISSUE TITLE
「プロジェクトを理解するためのReactデザインパターン」の画像が1つ、表示不可能になっている

### ISSUE THREAD

**Issue by mehm8128** [saku-1101/zenn-articles#12]
https://zenn.dev/cybozu_frontend/articles/design-patterns-in-react#presentational%26container%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3:~:text=%E3%81%97%E3%81%9F%E3%81%A8%E3%81%8D%E3%81%AB-,Do%20you%20want%20me%3F,-%F0%9F%98%98
で「ホバー時の挙動」の画像が表示できなくなってしまっています

https://github.com/sakupi01/zenn-articles/commit/8c6dcccdf7d1e67b80f8664f0af5619a118222b1 で追加された`image.png`がhttps://github.com/sakupi01/zenn-articles/commit/c332c7443279821ced31466a97445b091d817b30 で削除されてしまっているのが原因っぽいです

![image](https://github.com/user-attachments/assets/3238d995-cec1-46ad-81e1-1035bcd161cb)

**Comment by sakupi01** [comment]
@mehm8128 
Issueありがとうございます！修正しました！
